// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rare.h"

#include "gen/rare_tilemap_0.h"
#include "gen/rare_tilemap_1.h"
#include "gen/rare_tilemap_2.h"
#include "gen/rare_tilemap_3.h"
#include "gen/rare_tilemap_4.h"
#include "gen/rare_tilemap_5.h"
#include "gen/rare_tilemap_6.h"
#include "gen/rare_tilemap_7.h"
#include "gen/rare_tilemap_8.h"
#include "gen/rare_tilemap_9.h"
#include "gen/rare_tilemap_10.h"
#include "gen/rare_tilemap_11.h"
#include "gen/rare_tilemap_12.h"
#include "gen/rare_tilemap_13.h"
#include "gen/rare_tilemap_14.h"
#include "gen/rare_tilemap_15.h"
#include "gen/rare_tilemap_16.h"
#include "gen/rare_tilemap_17.h"

#include "gen/rare_tiledef_0.h"
#include "gen/rare_tiledef_1.h"
#include "gen/rare_tiledef_2.h"
